### PR TITLE
Minimalized Javascript

### PR DESCRIPTION
**Pull request by michaelvogt**
Just plain HTML and Javascript

### CODE REVIEW

**Comment by michaelvogt** [comment]
I just left `Open index.html in a browser ...` in the read me, as this is directly supported with my IDE (Webstorm). 
Alternatively I use from time to time [Servez](https://greggman.github.io/servez/) to serve local files.

**Comment by PatrickAlphaC** [comment]
Thanks for making this!

I'm wondering... does it make sense to have two branches then? I want the people who found the video to be able to find the code from the video.

**Comment by michaelvogt** [comment]
Yes, I think it is a good idea to show your viewers how things work with pure Javascript. Even when it's unlikely that anyone would develop something non trivial this way.

Adding vitejs to the mix is already a huge improvement in terms of app architecture, having a useful base for (standards based) module usage available.

The next step is then of course to use a framework, for which the vitejs website offers lots of simple starter projects.
https://vitejs.dev/guide/#trying-vite-online. When you share this link somewhere, your viewers should have an easy way to get their projects started - in whichever framework they prefer. 

As mentioned, Snowpack could be an alternative to vitejs, offering about the same functionality
https://www.snowpack.dev/

**Comment by PatrickAlphaC** [comment]
Closing this in favor of https://github.com/PatrickAlphaC/html-js-ethers-connect/pull/2

We will add vitejs as another branch :)

Thanks again!

**Pull request closed without merging**
